blank_issues_enabled: false
contact_links:
  - name: General feedback & comments
    url: https://www.figma.com/community/plugin/1640887971843572997
    about: For casual feedback and comments, leave a note on the Figma Community page.
